"""empty message

Revision ID: 0e6f91fd35a9
Revises: 2fbb04edb5ee
Create Date: 2021-03-03 23:39:10.396351

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0e6f91fd35a9'
down_revision = '2fbb04edb5ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('read', 'category')
    op.drop_column('read', 'notecreatedata')
    op.drop_column('read', 'note')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('read', sa.Column('note', mysql.TEXT(), nullable=True))
    op.add_column('read', sa.Column('notecreatedata', mysql.DATETIME(), nullable=False))
    op.add_column('read', sa.Column('category', mysql.VARCHAR(length=80), nullable=False))
    # ### end Alembic commands ###
