"""empty message

Revision ID: 246b8f5c2939
Revises: b5e5b267aae0
Create Date: 2021-03-04 13:22:46.206081

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '246b8f5c2939'
down_revision = 'b5e5b267aae0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('read_ibfk_2', 'read', type_='foreignkey')
    op.drop_column('read', 'feed_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('read', sa.Column('feed_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('read_ibfk_2', 'read', 'feed', ['feed_id'], ['id'])
    # ### end Alembic commands ###
