"""empty message

Revision ID: 267ce1be894f
Revises: 246b8f5c2939
Create Date: 2021-03-04 18:15:02.833166

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '267ce1be894f'
down_revision = '246b8f5c2939'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('note', 'notecreatedata',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_constraint('note_ibfk_2', 'note', type_='foreignkey')
    op.drop_column('note', 'feed_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('feed_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('note_ibfk_2', 'note', 'feed', ['feed_id'], ['id'])
    op.alter_column('note', 'notecreatedata',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
