"""empty message

Revision ID: 6c2c6ed24e7d
Revises: b5fb1a638d32
Create Date: 2021-03-02 23:36:26.449254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c2c6ed24e7d'
down_revision = 'b5fb1a638d32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry', sa.Column('updateddate', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entry', 'updateddate')
    # ### end Alembic commands ###
