"""empty message

Revision ID: 90f00d8c799b
Revises: f8d8ad776339
Create Date: 2021-04-27 14:51:41.915640

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '90f00d8c799b'
down_revision = 'f8d8ad776339'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entry', 'title',
               existing_type=mysql.VARCHAR(length=80),
               type_=sa.String(length=180),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entry', 'title',
               existing_type=sa.String(length=180),
               type_=mysql.VARCHAR(length=80),
               existing_nullable=False)
    # ### end Alembic commands ###
