"""empty message

Revision ID: f8d8ad776339
Revises: 440555c2c5dd
Create Date: 2021-04-27 14:49:42.879592

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f8d8ad776339'
down_revision = '440555c2c5dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feed', 'title',
               existing_type=mysql.VARCHAR(length=80),
               type_=sa.String(length=180),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feed', 'title',
               existing_type=sa.String(length=180),
               type_=mysql.VARCHAR(length=80),
               existing_nullable=False)
    # ### end Alembic commands ###
